#!/usr/bin/env bash

# $0 - полный путь к выполняемому скрипту

DIR="$( cd "$(dirname "$0")" && pwd )"

BACKUP=$DIR/backup
LOCATIONS=$DIR/backup.locations
TARGET=/tmp/backup
NUMBER=7
TIMESTAMP=$(date +%Y_%m_%d_%H_%M_%S)

# grep -v ^# $LOCATIONS | while IFS=";" read USER LOCATION T1 N1; do
# done

while IFS=";" read USER LOCATION T1 N1; do
	# игнорировать строчки, которые начинаются с #
	[[ "$USER" =~ ^#.*$ ]] && continue
	
	# если user пустой или location пустой - игнорировать
	[ -z "$USER" -o -z "$LOCATION" ] && continue
	
	T2=${T1:-$TARGET}/$USER
	N2=${N1:-$NUMBER}
	
	#echo $BACKUP $USER $LOCATION $T2 $N2 $TIMESTAMP
	$BACKUP $LOCATION $T2 $TIMESTAMP
done < $LOCATIONS