#!/bin/bash

# $@ => "$1" "$2" ...
function error() { cat <<< "$@" 1>&2; }

function help_message() {
	echo "Usage: $(basename $0) DIR TARGET
	where DIR is directory to backup"
}

function do_or_die() {
	# $1 - command, $2 - error message
	eval $1
	
	#if [[ $? != 0 ]]
	#if [ $? -ne 0 ]; then; ... fi	
	
	if [ $? -ne 0 ]; then
		error $2
		exit $?
	fi
}

# $1 = /etc/profile.d
# $2 = target
# $3 = timestamp

# if [ ! "$1" ]; then
if [ -z "$1" -o -z "$2" ]; then
	error "something missing"
	help_message
	exit 1
fi

TARGET=$2
#BNAME=`basename $1`
BNAME=$(basename $1)
DNAME=$(dirname $1)
FILE=$TARGET/${BNAME}_${3}.tgz

# 1.
#if [ ! -d $TARGET ]; then
#	mkdir $TARGET
#fi

# 2.
# if [ ! -d $TARGET ]; then; mkdir $TARGET; fi

# 3.
[ -d $TARGET ] || do_or_die "mkdir -p $TARGET" "mkdir $TARGET failed"

do_or_die "tar czf $FILE -C $DNAME $BNAME" "tar failed"