#!/bin/bash

# $@ => "$1" "$2" ...
function error() { cat <<< "$@" 1>&2; }

#if [ -z "$1" ]; then
if [ ! "$1" ]; then
	error "no directory"
	exit 1
fi

TARGET=/tmp/backup
FILE=$TARGET/$2.tar

mkdir $TARGET
tar cf $FILE $1
gzip -f -9 $FILE